### ISSUE TITLE
i can only play on 2x payout

### ISSUE THREAD

**Issue by pascal2313** [Norikiru/bloxflip-autocrash#54]
hi if i set it to 3x payout it wil not join a game only when i set it to 2x it works again

**Comment by carince** [comment]
This is maybe because your balance is not enough for 3x auto cashout.

Lets say you have 168 R$, the equation to calculating your bet size is: $`x/y^z`$
Where **x** is your balance, **y** is your auto cashout, and **z** is your tries/max losses.

While we have enough balance to do 2x at 14 tries:
$168/2^{14}=0.01$
We don't have enough balance to do 3x at 14 tries since lowest bet that Bloxflip allows is 0.01 R$:
$168/3^{14}=0.00003$

Unless... we lower our tries:
$168/3^8=0.02$
