### ISSUE TITLE
OS rain notification not working

### ISSUE THREAD

**Issue by starbuckson9** [Norikiru/bloxflip-autocrash#72]
![Screenshot_2](https://github.com/carince/bloxflip-autogambler/assets/56242171/2c4480a2-1d08-4ba9-ab34-e9b29b0ae288)

**Comment by carince** [comment]
I forgot to add the code to make the os notifs work when I made v3, anyways fixed with a new commit in the *dev* branch. Probably won't be pushed into the main branch soon though since I am implementing a rain autojoiner which prevents me from merging it in without breaking shit. 

Commit: https://github.com/carince/bloxflip-autogambler/commit/9e4088431d72c163ca593a461a3e9c92da73c44d

**Comment by starbuckson9** [comment]
wow thats nice, cant wait to have v3

**Comment by carince** [comment]
> wow thats nice, cant wait to have v3

v3 has already been released, you just need to do `git pull` in the bloxflip-autocrash folder to pull the updates, run `npm i` to install dependencies, and redo your config to the new format then hopefully it should run.
